
project_id = "hxhqzycgpdjzjrowyjxn"

[functions.facebook-ads]
verify_jwt = true

[functions.send-contract]
verify_jwt = true

[functions.generate-insights]
verify_jwt = true

[functions.google-ads-auth]
verify_jwt = false

[functions.google-ads-metrics]
verify_jwt = true
