// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxhqzycgpdjzjrowyjxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4aHF6eWNncGRqempyb3d5anhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNTA3NDcsImV4cCI6MjA1NTcyNjc0N30.3k2L9OPTFJuz6hB0BThijyzvw4n4QdgPBIfuiqxL8Vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);